# Toolchain file for building for VG5000 with z88dk toolchain
#
# use -DCMAKE_TOOLCHAIN_FILE=z88dk-cyos.cmake
#

set(CMAKE_SYSTEM_NAME cyos)
set(CMAKE_SYSTEM_PROCESSOR Z80)
set(CMAKE_C_COMPILER_ID z88dk)
set(CMAKE_ASM_COMPILER_ID z88dk)

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
# set(CMAKE_TRY_COMPILE_TARGET_TYPE EXECUTABLE)

set(TOOLCHAIN_PREFIX z88dk)
set(CMAKE_C_COMPILER ${TOOLCHAIN_PREFIX}.zcc)
set(CMAKE_ASM_COMPILER ${TOOLCHAIN_PREFIX}.zcc)
set(CMAKE_DEPENDS_USE_COMPILER True)

set(CMAKE_C_COMPILE_OBJECT  "<CMAKE_C_COMPILER> +embedded <DEFINES> <INCLUDES> <FLAGS> -o <OBJECT> -c <SOURCE>")
set(CMAKE_C_LINK_EXECUTABLE "<CMAKE_C_COMPILER> +embedded <FLAGS> <OBJECTS> -o <TARGET> <CMAKE_C_LINK_FLAGS> <LINK_FLAGS> <LINK_LIBRARIES>")

set(CMAKE_ASM_COMPILE_OBJECT  "<CMAKE_C_COMPILER> +embedded <DEFINES> <INCLUDES> <FLAGS> -o <OBJECT> -c <SOURCE>")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE NEVER)
